### ISSUE TITLE
AdminUI doesn't access to endpoint

### ISSUE THREAD

**Issue by leonardoheis** [brunohbrito/JPProject.IdentityServer4.AdminUI#210]
**Need Help to configurate JP Project Light Install**

- I'm trying to connect my IdentityServer4 project with the Light Admin UI and I faced some issues in order to access to the end points that solution provides.

- On the other hand the JPProject.Admin.Api doesn't provide the whole controller that are visualized in the front end part, in others words the front end present 6 options to be used and the light backend only implement 4.

**The error faced is**
1. Access to the Admin portal
2. Click on Clients option
3. In the JPProject.Admin.Api console appears this:

> [12:45:42 INF] Request starting HTTP/2 OPTIONS https://localhost:5103/clients
[12:45:42 INF] CORS policy execution successful.
[12:45:42 INF] Request finished in 47.9461ms 204
[12:45:42 INF] Request starting HTTP/2 GET https://localhost:5103/clients
[12:45:42 INF] CORS policy execution successful.
[12:45:42 INF] Successfully validated the token.
[12:45:42 DBG] AuthenticationScheme: Bearer was successfully authenticated.
[12:45:42 INF] Authorization was successful.
[12:45:42 INF] Executing endpoint 'JPProject.Admin.Api.Controllers.ClientsController.ListClients (JPProject.Admin.Api)'
[12:45:42 INF] Route matched with {action = "ListClients", controller = "Clients"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.Collections.Generic.IEnumerable`1[JPProject.Admin.Application.ViewModels.ClientsViewModels.ClientListViewModel]]] ListClients() on controller JPProject.Admin.Api.Controllers.ClientsController (JPProject.Admin.Api).
[12:45:42 INF] Executed action JPProject.Admin.Api.Controllers.ClientsController.ListClients (JPProject.Admin.Api) in 4.1798ms
[12:45:42 INF] Executed endpoint 'JPProject.Admin.Api.Controllers.ClientsController.ListClients (JPProject.Admin.Api)'
[12:45:43 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'MediatR.INotificationHandler`1[JPProject.Domain.Core.Notifications.DomainNotification]' while attempting to activate 'JPProject.Admin.Api.Controllers.ClientsController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
[12:45:43 INF] Executing ObjectResult, writing value of type 'Hellang.Middleware.ProblemDetails.DeveloperProblemDetails'.
[12:45:43 INF] Request finished in 313.6046ms 500 application/problem+json; charset=utf-8

**Additional consideration**
If you need some configuration I made please let me know in order to add it

Hope you can help me.
Thanks
Leo

**Comment by brunohbrito** [comment]
Hi @leonardoheis,

> On the other hand the JPProject.Admin.Api doesn't provide the whole controller that are visualized in the front end part, in others words the front end present 6 options to be used and the light backend only implement 4.

I've classified it in two versions, Light, which you are using, and full.

In API of Light version there are only endpoints to make changes to IdentityServer4 Database. Therefore, there are 6 endpoints in Admin-ui, but only 4 at API.

The others features are strict related to ASP.NET Identity, you can develop it, or get the Full version (SSO), them this endpoints will be available.

> I'm trying to connect my IdentityServer4 project with the Light Admin UI and I faced some issues in order to access to the end points that solution provides.

After a few tests, setup some environments, I guess that got it. I'll make a PR asap

**Comment by brunohbrito** [comment]
plz check again.
