### ISSUE TITLE
Unable to run via docker compose

### ISSUE THREAD

**Issue by tracker1** [brunohbrito/JPProject.IdentityServer4.AdminUI#48]
Currently running the docker compose file, via the listed link... saved as docker-compose.prod.yml.  On the latest Docker Desktop on Windows 

Version: 2.0.5.0 (35318)
Channel: Edge
Engine: 19.03.0-rc2
Compose: 1.24.0

[docker-compose.prod.yml](https://raw.githubusercontent.com/brunohbrito/JPProject.IdentityServer4.AdminUI/master/build/docker-compose.yml)

`docker-compose -f docker-compose.prod.yml up`

Getting the following error:
```
jpproject_1      | [23:52:58 Debug] IdentityServer4.Startup
jpproject_1      | Error Id Parameter: errorId
jpproject_1      |
jpproject_1      | [23:53:16 Information] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
jpproject_1      | AuthenticationScheme: Identity.Application was challenged.
jpproject_1      |
jpproject_1      | [23:53:16 Error] Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery
jpproject_1      | An exception was thrown while deserializing the token.
jpproject_1      | Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {25c2ca98-93f7-44b8-9e45-de60cdcad3d1} was not found in the key ring.
jpproject_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
jpproject_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean&
requiresMigration, Boolean& wasRevoked)
jpproject_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
jpproject_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
jpproject_1      |    --- End of inner exception stack trace ---
jpproject_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
jpproject_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
jpproject_1      |
jpproject_1      | [23:53:32 Debug] IdentityServer4.Hosting.CorsPolicyProvider
jpproject_1      | CORS request made for path: /Account/Login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
jpproject_1      |
jpproject_1      | [23:53:32 Warning] Microsoft.AspNetCore.Identity.UserManager
jpproject_1      | Invalid password for user 08d7097d-6b71-de76-6b6c-b29852be12fb.
jpproject_1      |
jpproject_1      | [23:53:32 Warning] Microsoft.AspNetCore.Identity.SignInManager
jpproject_1      | User 08d7097d-6b71-de76-6b6c-b29852be12fb failed to provide the correct password.
jpproject_1      |
jpproject_1      | [23:53:32 Information] IdentityServer4.Events.DefaultEventService
jpproject_1      | {"Username": "bruno", "Endpoint": "UI", "Category": "Authentication", "Name": "User Login Failure", "EventType": "Failure", "Id": 1001, "Message": "invalid credentials", "ActivityId": "0HLO9FU85GPAB:00000006", "TimeStamp": "2019-07-15T23:53:32.0000000Z", "ProcessId": 1, "LocalIpAddress": "::ffff:172.19.0.4:5000", "RemoteIpAddress": "::ffff:172.19.0.1", "$type": "UserLoginFailureEvent"}
```

When  I tried the latest via the master branch, it was giving me a credential error...
[docker-compose.yml](https://github.com/brunohbrito/JPProject.IdentityServer4.AdminUI/blob/master/docker-compose.yml)

```
jpproject_1      | [23:45:27 Warning] Microsoft.AspNetCore.Identity.SignInManager
jpproject_1      | User 08d7097d-6b71-de76-6b6c-b29852be12fb is currently locked out.
jpproject_1      |
jpproject_1      | [23:45:27 Information] IdentityServer4.Events.DefaultEventService
jpproject_1      | {"Username": "bruno", "Endpoint": "UI", "Category": "Authentication", "Name": "User Login Failure", "EventType": "Failure", "Id": 1001, "Message": "invalid credentials", "ActivityId": "0HLO9FQ1HTKB1:00000001", "TimeStamp": "2019-07-15T23:45:27.0000000Z", "ProcessId": 1, "LocalIpAddress": "::ffff:172.19.0.3:5000", "RemoteIpAddress": "::ffff:172.19.0.1", "$type": "UserLoginFailureEvent"}
```

**Comment by tracker1** [comment]
I am brand spanking new to the project, and really wanting/needing to get more familiar with it.  Need to add a few admin and password reset options as well as wanting to add a SQLite adapter (using a shared named volume), and create a compose file for running locally against sql server.

**Comment by tracker1** [comment]
Okay, I was grabbing the password out of the compose file...

`ApplicationSettings:DefaultPass: Pa$$word123` and apparently, the actual password comes out as `Pa$word123` guessing it's an escape for `$` in docker-compose?

**Comment by tracker1** [comment]
Also, neglected to add jpproject to my hosts file.

**Comment by brunohbrito** [comment]
Hi @tracker1,

Thanks for your resolving your own issue. Btw the only solution I could figure out how to use it in Docker is changing hosts file.

Indeed this solution I got from official IdentityServer Admin
